#!/usr/bin/env python3

from __future__ import annotations

import argparse
import html
import json
from datetime import datetime
from pathlib import Path
from typing import Any


ROOT_DIR = Path(__file__).resolve().parents[2]
SERVICE_ACCOUNT = ROOT_DIR / "env" / "mileagethief-firebase-adminsdk-8gdf2-49e348f31e.json"
_FIREBASE_ADMIN: Any = None
_CREDENTIALS: Any = None
_FIRESTORE: Any = None

AUTHOR = {
    "uid": "aP3C0N511beyK7QZG9GyChs5oqO2",
    "displayName": "오늘의 좌석",
    "photoURL": "https://firebasestorage.googleapis.com/v0/b/mileagethief.firebasestorage.app/o/users%2FaP3C0N511beyK7QZG9GyChs5oqO2.png?alt=media&token=5e0ddec7-45ad-4f0e-b83e-485ee1babf1d",
    "displayGrade": "★★★",
    "currentSkyEffect": "",
}

AIRPORT_NAMES = {
    "ICN": "인천",
    "LAX": "로스앤젤레스",
    "JFK": "뉴욕",
    "HNL": "호놀룰루",
    "BCN": "바르셀로나",
    "DPS": "발리",
    "FCO": "로마",
    "CDG": "파리",
    "SYD": "시드니",
    "SGN": "호치민",
    "BNE": "브리즈번",
    "ZRH": "취리히",
    "BKK": "방콕",
    "YVR": "밴쿠버",
    "FRA": "프랑크푸르트",
    "SFO": "샌프란시스코",
    "SIN": "싱가포르",
    "LHR": "런던",
    "LAS": "라스베가스",
    "CXR": "나트랑",
    "HKT": "푸켓",
    "PQC": "푸꾸옥",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Upload normalized Korean Air award availability into Firestore and posts.",
    )
    parser.add_argument("--input", required=True, help="JSON generated by capture_korean_air_award.js.")
    parser.add_argument("--dry-run", action="store_true", help="Print write targets without Firestore writes.")
    parser.add_argument("--skip-post-upload", action="store_true", help="Only upload dan snapshots.")
    return parser.parse_args()


def firebase_modules() -> tuple[Any, Any, Any]:
    global _FIREBASE_ADMIN, _CREDENTIALS, _FIRESTORE
    if _FIREBASE_ADMIN is None or _CREDENTIALS is None or _FIRESTORE is None:
        import firebase_admin
        from firebase_admin import credentials, firestore

        _FIREBASE_ADMIN = firebase_admin
        _CREDENTIALS = credentials
        _FIRESTORE = firestore
    return _FIREBASE_ADMIN, _CREDENTIALS, _FIRESTORE


def server_timestamp() -> Any:
    return firebase_modules()[2].SERVER_TIMESTAMP


def initialize_firebase() -> Any:
    if not SERVICE_ACCOUNT.exists():
        raise FileNotFoundError(f"Service account file not found: {SERVICE_ACCOUNT}")
    firebase_admin, credentials, firestore = firebase_modules()
    if not firebase_admin._apps:
        cred = credentials.Certificate(str(SERVICE_ACCOUNT))
        firebase_admin.initialize_app(cred)
    return firestore.client()


def load_payload(path: str) -> dict[str, Any]:
    input_path = Path(path).expanduser().resolve()
    with input_path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload.get("routeResults"), dict):
        raise ValueError("input.routeResults must be an object")
    return payload


def has_cabin(entry: dict[str, Any], cabin: str) -> bool:
    seat = entry.get(cabin)
    if not isinstance(seat, dict):
        return False
    return bool(str(seat.get("amount") or seat.get("mileage") or "").strip())


def table_row(date_key: str, entry: dict[str, Any]) -> str:
    biz_icon = "🟢" if has_cabin(entry, "business") else "🔴"
    first_icon = "🟢" if has_cabin(entry, "first") else "🔴"
    cell_style = "border:1px solid #ccc; padding:8px; text-align:center; margin:0;"
    return (
        f"<tr><td style='{cell_style}'>{html.escape(date_key)}</td>"
        f"<td style='{cell_style}'>{biz_icon}</td>"
        f"<td style='{cell_style}'>{first_icon}</td></tr>"
    )


def build_table(rows: list[str], include_margin: bool = False) -> str:
    margin = " margin-top:5px;" if include_margin else ""
    header_style = "border:1px solid #ccc; padding:8px; background-color:#f0f0f0; text-align:center; margin:0;"
    return (
        f"<table style='width:100%; font-size:14px;{margin} border-spacing:0;'>"
        f"<tr><th style='{header_style}'>날짜</th>"
        f"<th style='{header_style}'>비즈니스</th>"
        f"<th style='{header_style}'>퍼스트</th></tr>"
        + "".join(rows)
        + "</table>\n"
    )


def route_section(route_key: str, seats_by_date: dict[str, Any], label: str) -> str:
    departure, arrival = route_key.split("-", 1)
    available_rows: list[tuple[str, dict[str, Any]]] = []
    for date_key in sorted(seats_by_date):
        entry = seats_by_date.get(date_key)
        if not isinstance(entry, dict):
            continue
        if has_cabin(entry, "business") or has_cabin(entry, "first"):
            available_rows.append((date_key, entry))

    display_city = AIRPORT_NAMES.get(arrival, arrival)
    h2 = (
        f"<h2 style='color:#0d47a1;'>"
        f"{html.escape(departure)} → {html.escape(arrival)} ({html.escape(display_city)}) / {label}"
        f"</h2>\n"
    )
    main_rows = [table_row(date_key, entry) for date_key, entry in available_rows[:5]]
    details_rows = [table_row(date_key, entry) for date_key, entry in available_rows]
    section = h2 + build_table(main_rows)
    if len(details_rows) > 5:
        section += (
            "<details><summary style='margin-top:10px; font-weight:bold; color:#0d47a1;'>"
            "▼ 더 보기 (전체)"
            "</summary>"
            + build_table(details_rows, include_margin=True)
            + "</details>\n"
        )
    return section + "\n"


def display_time_from_payload(payload: dict[str, Any]) -> tuple[str, str, str]:
    timestamp_key = str(payload.get("timestampKey") or "")
    if len(timestamp_key) < 10:
        now = datetime.now()
        timestamp_key = now.strftime("%Y%m%d%H%M")
    date_string = timestamp_key[:8]
    hour_string = timestamp_key[8:10]
    dt = datetime.strptime(date_string + hour_string, "%Y%m%d%H")
    display_label = f"{dt.year}년 {dt.month}월 {dt.day}일 {hour_string}시"
    return date_string, hour_string, display_label


def build_content_html(payload: dict[str, Any]) -> str:
    route_results = payload["routeResults"]
    date_string, _, display_label = display_time_from_payload(payload)
    days_ahead = int(payload.get("daysAhead") or 360)
    content = (
        f'<h1 style="text-align:center; color:#1a237e;">✈️ {display_label} 현재 '
        "대한항공 마일리지 좌석 정보 (비즈니스 / 퍼스트)</h1>\n"
        f'<p style="text-align:center;">조회일 기준 {days_ahead}일 중 일부 샘플 | 접기/펼치기 기능 포함</p>\n\n'
    )

    rendered: set[str] = set()
    requested_routes = payload.get("requestedRoutes") or []
    for route in requested_routes:
        departure = str(route.get("departure") or route.get("departureAirport") or "").upper()
        arrival = str(route.get("arrival") or route.get("arrivalAirport") or "").upper()
        if not departure or not arrival:
            continue
        for route_key, label in ((f"{departure}-{arrival}", "가는편"), (f"{arrival}-{departure}", "오는편")):
            result = route_results.get(route_key) or {}
            seats_by_date = result.get("seatsByDate") if isinstance(result, dict) else {}
            if not isinstance(seats_by_date, dict):
                seats_by_date = {}
            content += route_section(route_key, seats_by_date, label)
            rendered.add(route_key)

    for route_key in sorted(set(route_results) - rendered):
        result = route_results.get(route_key) or {}
        seats_by_date = result.get("seatsByDate") if isinstance(result, dict) else {}
        if isinstance(seats_by_date, dict):
            content += route_section(route_key, seats_by_date, "조회")

    # date_string is intentionally evaluated here so invalid timestamps fail before upload.
    if len(date_string) != 8:
        raise ValueError(f"Invalid date string derived from timestampKey: {date_string}")
    return content


def build_post_data(
    payload: dict[str, Any],
    post_exists: bool,
    include_timestamps: bool = True,
) -> tuple[str, str, dict[str, Any]]:
    date_string, hour_string, display_label = display_time_from_payload(payload)
    post_id = f"KE-{date_string}{hour_string}"
    title = f"✈️ {display_label} 현재 대한항공 마일리지 좌석 정보 (비즈니스/퍼스트)"
    post_data: dict[str, Any] = {
        "postId": post_id,
        "postNumber": post_id,
        "boardId": "seats",
        "title": title,
        "contentHtml": build_content_html(payload),
        "author": AUTHOR,
        "viewsCount": 0,
        "likesCount": 0,
        "commentCount": 0,
        "reportsCount": 0,
        "isDeleted": False,
        "isHidden": False,
        "hiddenByReport": False,
    }
    if include_timestamps:
        post_data["updatedAt"] = server_timestamp()
        if not post_exists:
            post_data["createdAt"] = server_timestamp()
    return date_string, post_id, post_data


def normalized_seats_by_date(result: dict[str, Any]) -> dict[str, dict[str, dict[str, str]]]:
    seats_by_date = result.get("seatsByDate") or {}
    if not isinstance(seats_by_date, dict):
        return {}

    normalized: dict[str, dict[str, dict[str, str]]] = {}
    for date_key, entry in seats_by_date.items():
        if not isinstance(date_key, str) or len(date_key) != 8:
            continue
        if not isinstance(entry, dict):
            continue
        seat_payload: dict[str, dict[str, str]] = {}
        for seat_class in ("economy", "business", "first"):
            seat = entry.get(seat_class)
            if not isinstance(seat, dict):
                continue
            amount = str(seat.get("amount") or "").strip()
            mileage = str(seat.get("mileage") or "").strip()
            if amount or mileage:
                seat_payload[seat_class] = {"amount": amount, "mileage": mileage}
        if seat_payload:
            normalized[date_key] = seat_payload
    return normalized


def print_dry_run(payload: dict[str, Any], skip_post_upload: bool) -> None:
    timestamp_key = str(payload.get("timestampKey"))
    print(f"[dry-run] timestampKey={timestamp_key}")
    for route_key, result in sorted(payload["routeResults"].items()):
        if not isinstance(result, dict):
            continue
        seats = normalized_seats_by_date(result)
        print(f"[dry-run] dan/{route_key}/{timestamp_key}/snapshot dates={len(seats)}")
        print(f"[dry-run] dan/{route_key}/latest/meta id={timestamp_key}")
    if not skip_post_upload:
        date_string, post_id, post_data = build_post_data(
            payload,
            post_exists=False,
            include_timestamps=False,
        )
        print(f"[dry-run] posts/{date_string}/posts/{post_id}")
        print(f"[dry-run] title={post_data['title']}")
        print(f"[dry-run] contentHtmlBytes={len(post_data['contentHtml'].encode('utf-8'))}")


def upload(payload: dict[str, Any], skip_post_upload: bool) -> None:
    timestamp_key = str(payload.get("timestampKey") or "").strip()
    if not timestamp_key:
        raise ValueError("input.timestampKey is required")

    db = initialize_firebase()
    batch = db.batch()
    route_write_count = 0

    for route_key, result in sorted(payload["routeResults"].items()):
        if not isinstance(result, dict):
            continue
        departure = str(result.get("departureAirport") or route_key.split("-", 1)[0]).upper()
        arrival = str(result.get("arrivalAirport") or route_key.split("-", 1)[1]).upper()
        seats_by_date = normalized_seats_by_date(result)

        snapshot_ref = (
            db.collection("dan")
            .document(route_key)
            .collection(timestamp_key)
            .document("snapshot")
        )
        latest_ref = db.collection("dan").document(route_key).collection("latest").document("meta")
        snapshot_data = {
            "departureAirport": departure,
            "arrivalAirport": arrival,
            "seatsByDate": seats_by_date,
            "sourceProvider": payload.get("sourceProvider") or "korean_air_bonus_seat_view_api",
            "sourceRunId": payload.get("runId"),
            "updatedAt": server_timestamp(),
        }
        batch.set(snapshot_ref, snapshot_data)
        batch.set(latest_ref, {"id": timestamp_key, "updatedAt": server_timestamp()})
        route_write_count += 2

    if not skip_post_upload:
        date_string, post_id, _ = build_post_data(
            payload,
            post_exists=False,
            include_timestamps=False,
        )
        post_ref = db.collection("posts").document(date_string).collection("posts").document(post_id)
        post_exists = post_ref.get().exists
        _, _, post_data = build_post_data(payload, post_exists=post_exists)
        batch.set(post_ref, post_data, merge=True)
        route_write_count += 1

    batch.commit()
    print(f"[upload] committedWrites={route_write_count}")


def main() -> None:
    args = parse_args()
    payload = load_payload(args.input)
    if args.dry_run:
        print_dry_run(payload, args.skip_post_upload)
        return
    upload(payload, args.skip_post_upload)


if __name__ == "__main__":
    main()
