name: mileage_thief
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.1.12+52

environment:
  sdk: '>=3.0.0-218.0.dev <4.0.0'
dependencies:
  dropdown_search: ^5.0.5
  dropdown_button2: ^2.3.9
  firebase_core: ^3.1.0
  firebase_database: ^11.0.1
  flutter_native_splash: ^2.2.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^3.1.2
  share_plus: ^11.0.0
  google_mobile_ads: ^5.1.0
  url_launcher: ^6.1.11
  firebase_analytics: ^11.0.1
  shared_preferences: ^2.0.18
  fluttertoast: ^8.2.1
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.2.1+2
  table_calendar: ^3.1.3
  intl: ^0.20.2
  flutter_custom_month_picker: ^0.1.3
  settings_ui: ^2.0.2
  package_info_plus: ^8.3.0
  cloud_firestore: ^5.6.8
  month_picker_dialog: ^6.0.3
  firebase_auth: ^5.1.0
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3
  uuid: ^4.0.0
  appflowy_editor:
    git:
      url: https://github.com/mungyuchoi/appflowy-editor.git
      ref: main
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - asset/img/

  fonts:
    - family: Ssuk
      fonts:
        - asset: asset/font/Cafe24Ssukssuk.ttf
    - family: Oneprettynight
      fonts:
        - asset: asset/font/Cafe24Oneprettynight.ttf
    - family: Ohsquareair
      fonts:
        - asset: asset/font/Cafe24Ohsquareair.ttf
    - family: Ssuround
      fonts:
        - asset: asset/font/Cafe24SSurround.ttf
    - family: SsuroundAir
      fonts:
        - asset: asset/font/Cafe24SSurroundAir.ttf
    - family: NanumGothic
      fonts:
        - asset: asset/font/NanumGothic.ttf
        - asset: asset/font/NanumGothicBold.ttf
          weight: 700
        - asset: asset/font/NanumGothicExtraBold.ttf
          weight: 800

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/img/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true # iOS App Store에서 알파 채널 제거