name: mileage_thief
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.4+5

environment:
  sdk: '>=3.0.0-218.0.dev <4.0.0'
dependencies:
  dropdown_search: ^5.0.5
  dropdown_button2: ^1.9.2
  firebase_core: ^2.5.0
  firebase_database: ^10.0.11
  flutter_native_splash: ^2.2.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^2.2.0
  share: ^2.0.4
  google_mobile_ads: 2.3.0
  url_launcher: ^6.0.6
  firebase_analytics: ^10.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - asset/img/
  fonts:
    - family: Ssuk
      fonts:
        - asset: asset/font/Cafe24Ssukssuk.ttf
    - family: Oneprettynight
      fonts:
        - asset: asset/font/Cafe24Oneprettynight.ttf
    - family: Ohsquareair
      fonts:
        - asset: asset/font/Cafe24Ohsquareair.ttf
    - family: Ssuround
      fonts:
        - asset: asset/font/Cafe24SSurround.ttf
    - family: SsuroundAir
      fonts:
        - asset: asset/font/Cafe24SSurroundAir.ttf