// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_fZP-lWVpYAAK1aojIa861rV0NLTJj2Q',
    appId: '1:962527268971:web:35281f6ace9b6029e4612e',
    messagingSenderId: '962527268971',
    projectId: 'mileagethief',
    authDomain: 'mileagethief.firebaseapp.com',
    databaseURL: 'https://mileagethief-default-rtdb.firebaseio.com',
    storageBucket: 'mileagethief.appspot.com',
    measurementId: 'G-249Q0QVZGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiCV99gNYFaTrsI-0pMBRYy6Fm_PbAzLE',
    appId: '1:962527268971:android:cf36cfc6e06f17d0e4612e',
    messagingSenderId: '962527268971',
    projectId: 'mileagethief',
    databaseURL: 'https://mileagethief-default-rtdb.firebaseio.com',
    storageBucket: 'mileagethief.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGAgbK-9qurqHVQPdDVrxlXC92N2PIcZ0',
    appId: '1:962527268971:ios:d6efb76824deb711e4612e',
    messagingSenderId: '962527268971',
    projectId: 'mileagethief',
    databaseURL: 'https://mileagethief-default-rtdb.firebaseio.com',
    storageBucket: 'mileagethief.appspot.com',
    iosClientId: '962527268971-6de9mcd4hgtahu7f39o1a2le5gl9d7oi.apps.googleusercontent.com',
    iosBundleId: 'com.mungyu.mileageThief',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGAgbK-9qurqHVQPdDVrxlXC92N2PIcZ0',
    appId: '1:962527268971:ios:0a1ad1ee8f8e5e25e4612e',
    messagingSenderId: '962527268971',
    projectId: 'mileagethief',
    databaseURL: 'https://mileagethief-default-rtdb.firebaseio.com',
    storageBucket: 'mileagethief.appspot.com',
    iosClientId: '962527268971-evrs201opu4h72a4q5l6h6lk52rruro0.apps.googleusercontent.com',
    iosBundleId: 'com.mungyu.mileageThief.RunnerTests',
  );
}
